title: Shahul Hameed Udhuman
description: Senior Technical Architect · Cloud · Microservices · AI Enablement
markdown: kramdown
permalink: /blogs/:title/
url: "https://shameed.github.io"
baseurl: ""

future: true
